# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.3"
  - "2.7"
  - "2.6"
  - "pypy"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install coverage coveralls -r requirements.txt -r test-requirements.txt

# command to run tests, e.g. python setup.py test
script: coverage run -m testtools.run discover

after_success:
    coveralls
